"""Speech recognition, against real audio.

These tests need the Whisper assets (`scripts/fetch_models.py --model asr`) and are
skipped without them, so CI on a bare checkout stays green. When the assets ARE present
they run the whole path - mel features, encoder, greedy decode, detokenise - because
every bug this code has had was invisible until real audio went through it:

  * the mel spectrogram produced 2998 frames where the encoder demands 3000, and failed
    with a broadcast error naming 1499 and 1500
  * the session cache keyed on the model name alone, so the decoder call was handed the
    cached encoder session
  * the filterbank used the HTK mel scale instead of Whisper's Slaney scale, which runs
    without error and transcribes noise - the worst failure mode of the three

`assets/sample_doctor.wav` is generated by Windows TTS (see docs/MODELS.md), so the
fixture is reproducible and carries no third-party speech.
"""

from __future__ import annotations

import wave
from pathlib import Path

import numpy as np
import pytest

from setu.config import Settings
from setu.models.asr import SAMPLE_RATE, log_mel_spectrogram
from setu.pipeline import ConsultAgent, Engine

REPO = Path(__file__).resolve().parents[1]
SAMPLE = REPO / "assets" / "sample_doctor.wav"
ASSETS = REPO / "models" / "asr" / "asr_encoder.onnx"

needs_whisper = pytest.mark.skipif(
    not (SAMPLE.is_file() and ASSETS.is_file()),
    reason="Whisper assets absent; run scripts/fetch_models.py --model asr",
)


def load_wav(path: Path) -> np.ndarray:
    with wave.open(str(path), "rb") as fh:
        pcm = np.frombuffer(fh.readframes(fh.getnframes()), dtype=np.int16)
    return pcm.astype(np.float32) / 32768.0


# ------------------------------------------------------------------ features


def test_mel_has_exactly_the_frames_the_encoder_demands():
    audio = np.zeros(SAMPLE_RATE * 3, dtype=np.float32)
    mel = log_mel_spectrogram(audio)
    assert mel.shape == (80, 3000), "Whisper's encoder is a fixed-shape graph"


def test_mel_is_normalised_into_the_trained_range():
    """Whisper clamps to an 8-decade dynamic range and divides by 4.

    So the output spans exactly 2.0, but it is anchored to the loudest bin rather than to
    zero - a quiet clip and a loud one both span 2.0 at different offsets. Asserting a
    fixed [-1, 1] box would be asserting something the reference implementation never
    promised.
    """
    rng = np.random.default_rng(0)
    mel = log_mel_spectrogram(rng.normal(0, 0.1, SAMPLE_RATE * 5).astype(np.float32))
    assert float(mel.max() - mel.min()) == pytest.approx(2.0, abs=1e-4)


def test_mel_filterbank_uses_the_slaney_scale():
    from setu.models.asr import _hz_to_mel

    # Slaney is linear below 1 kHz: 500 Hz sits at exactly 500 / (200/3) = 7.5 mel.
    # The HTK formula would give ~7.0 here, and a transcript of noise.
    assert float(_hz_to_mel(500.0)) == pytest.approx(7.5, abs=1e-6)


# ----------------------------------------------------------------- real audio


@pytest.fixture(scope="module")
def engine(tmp_path_factory):
    settings = Settings()
    tmp = tmp_path_factory.mktemp("asr")
    settings.data_dir = tmp
    settings.db_path = tmp / "setu.db"
    e = Engine(settings)
    yield e
    e.close()


@needs_whisper
def test_transcribes_real_speech(engine):
    result = engine.asr.transcribe(load_wav(SAMPLE), language="en")

    assert not result.degraded, "assets are present, so this must be a real inference"
    text = result.value.lower()
    keywords = [w for w in ("tablet", "night", "chest", "pain", "emergency") if w in text]
    assert len(keywords) >= 4, f"only matched {keywords} in {result.value!r}"


@needs_whisper
def test_transcript_feeds_the_comprehension_pipeline(engine):
    """The point of the ASR path: speech in, care plan out."""
    result = engine.asr.transcribe(load_wav(SAMPLE), language="en")
    agent = ConsultAgent(engine)
    agent.start("asr-e2e", patient_language="hi", domain="clinic")
    agent.add_turn("asr-e2e", "doctor", result.value)

    plan = agent.get("asr-e2e").plan
    kinds = {item.kind for item in plan}
    assert "redflag" in kinds, f"the emergency warning must be extracted, got {kinds}"
    assert "medication" in kinds


@needs_whisper
def test_silence_does_not_produce_confident_speech(engine):
    result = engine.asr.transcribe(np.zeros(SAMPLE_RATE * 4, dtype=np.float32), language="en")
    assert len(result.value) < 120, f"silence should not decode a paragraph: {result.value!r}"
